
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 418392
	#The name of the modpack
	modpackName = "Mo's Mods"
	#The version of the modpack
	modpackVersion = "v4.0.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

