#This is the application ID that you will find in the General Information tab on your application page on https://discord.com/developers/applications/.
applicationID = "927396521698263040"
#This is the text that will be show underneath the title of your application.
details = "A Terraria-Inspired Modpack"
#This is the text that will be show underneath the details.
state = "Being fine in a place in a time in a space"
#This is the name of your uploaded image that you want to be your large image on the application tab > Rich Presence > Art Assets.
largeImageKey = "TerraesqueIconTemp"
#This is the text that will show up when you hover over the large image.
largeImageText = "+100% More Blocky"
#This is the name of your uploaded image that you want to be your small image on the application tab > Rich Presence > Art Assets.
smallImageKey = "TerraesqueIconTemp"
#This is the text that will show up when you hover over the small image.
smallImageText = "No secret text here"
#Keep true if you want to see how long you have been playing underneath the state text.
timestampEnabled = true
#Keep true if you want to start the automated chat setup when the mod hasn't been setup yet
autoChatSetup = true

