
["Configurations for Full Turtle Armor [Forge Edition]"]
	#Should a full set of Turtle Armor grant Dolphin's Grace when underwater? [True = Yes, False = No]
	"Dolphin's Grace on Full Set" = true
	#Should a full set of Turtle Armor grant Nightvision when underwater? [True = Yes, False = No]
	"Nightvision on Full Set" = true

