
["Damage Enchantments"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Efficiency]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Fire Aspect"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Impaling]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Knockback]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Loot Bonus Enchantments"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Loyalty]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

[Lure]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

[Piercing]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Power]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Protection Enchantments"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Punch]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Quick Charge"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

[Respiration]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

[Riptide]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Soul Speed"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Sweeping Edge"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Thorns]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

[Unbreaking]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10

["Enchanter Villager"]
	# Whether the enchanter villager is enabled
	isEnabled = true

["Attack Reach"]
	# Whether the mod changes these enchantments
	isEnabled = false
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 1

["Block Reach"]
	# Whether the mod changes these enchantments
	isEnabled = false
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 3

["Cat Vision"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Camouflage]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Critical]
	# Whether the mod changes these enchantments
	isEnabled = false
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Cavernous Storage"]
	# Whether the mod changes these enchantments
	isEnabled = false
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

["Double Break"]
	# Whether the mod changes these enchantments
	isEnabled = false
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Fast Hopper"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

[Flight]
	# Whether the mod changes these enchantments
	isEnabled = false
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3

[Freezing]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 3

["Health Boost"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5

[Heavy]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5

[Reinforcement]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5

[Replanting]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1

["Step Assist"]
	# Whether the mod changes these enchantments
	isEnabled = false
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3

[Temper]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5

["Fast Smelt"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 1

["Fuel Efficient"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 1

["Extra Experience"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 1

["Heavy Blade"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5

["Light Blade"]
	# Whether the mod changes these enchantments
	isEnabled = true
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3

